######################################################################
# Automatically generated by qmake (3.0) ?? 1? 4 15:11:32 2016
######################################################################

TEMPLATE = app
TARGET = ser_read
INCLUDEPATH += .

QT += serialport
QT += widgets

# Input
SOURCES += ser_read.cpp
