######################################################################
# Automatically generated by qmake (3.0) ?? 1? 4 17:11:49 2016
######################################################################

TEMPLATE = app
TARGET = ser_rw
INCLUDEPATH += .

QT += core
QT += serialport
QT += widgets

# Input
SOURCES += ser_rw.cpp
