######################################################################
# Automatically generated by qmake (3.0) ?? 1? 5 11:21:12 2016
######################################################################

TEMPLATE = app
TARGET = ser_disp
INCLUDEPATH += .

QT += core
QT += widgets
QT += gui
QT += serialport

# Input
HEADERS += mainwindow.h
FORMS += mainwindow.ui
SOURCES += main.cpp mainwindow.cpp simpletest.cpp resultDisp.cpp
